### PR TITLE
fix: focus issue when we select either month or year in single month …

### LINKED ISSUE #294: From Date Range Picker "To date" is not selectable by selecting month and year from dopdown
### Describe the bug
As soon as I select **From** date from calendar the cursor moves to **To** date field but if I click on calendar to select the month/year then that cursor again comes to **From** date field and it selects again from date only.

### To Reproduce

1. Go to Date Range Picker calender and select month and year for from date 
2. Cursor moves to To date select to date by selected month and year from above month and year list and click on date 
3. It will selects from date again as cursor is again come back to from date on click of month and year list
4.Not able to select To date in this way 

### Expected behavior
User should able to select any month and year for To date from month and year list

### Screenshots
Screenshot 2021-06-15 at 2 55 23 PM

### Package versions
        "@medly-components/core": "^1.40.0",
        "@medly-components/forms": "^1.16.1",
        "@medly-components/layout": "^1.6.0",
        "@medly-components/loaders": "^1.0.39",
        "@medly-components/theme": "^1.28.0",
        "@medly-components/utils": "^1.8.3",

### PR DESCRIPTION
**Pull request by gmukul01**
…calendar view

affects: @medly-components/core

### PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] Tests for the changes have been added (for bug fixes / features)
-   [x] Docs have been added / updated (for bug fixes / features)

### PR Type

What kind of change does this PR introduce?

-   [x] Bugfix
-   [ ] Feature
-   [ ] Code style update (formatting, local variables)
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Build related changes
-   [ ] CI related changes
-   [ ] Performance improves
-   [ ] Adding missing tests
-   [ ] Documentation content changes
-   [ ] Other... Please describe:

### What is the current behavior?

As soon as we select From date from calendar the cursor moves to To date field but if I click on calendar to select the month/year then that cursor again comes to From date field and it selects again from date only.

### What is the new behavior?

As soon as we select From date from calendar the cursor moves to To date field and stays there after selecting month/year.

### Does this PR introduce a breaking change?

-   [ ] Yes
-   [x] No

### CODE REVIEW

File: packages/core/src/components/Calendar/MonthAndYearSelection/MonthAndYearSelection.tsx [hunk 1]
```diff
@@ -12,8 +12,8 @@ export const MonthAndYearSelection: React.FC<MonthAndYearSelectionProps> & WithS
             { month: maxMonth, year: maxYear } = getMonthAndYearFromDate(maxSelectableDate);
 
         const stopPropagation = useCallback(e => e.stopPropagation(), []),
-            handleMonthChange = useCallback((value: number) => onChange({ year: year, month: value }), [year]),
-            handleYearChange = useCallback((value: number) => onChange({ month: month, year: value }), [month]);
+            handleMonthChange = useCallback((value: number) => onChange({ year: year, month: value }), [year, onChange]),
```
Comment (wsameer) [inline packages/core/src/components/Calendar/MonthAndYearSelection/MonthAndYearSelection.tsx:15]: looks good

**Review by wsameer — APPROVED** [review]
LGTM 👍
