### PR TITLE
fix(forms): clear number input

### LINKED ISSUE #603: bug: cannot clear number input
### Describe the bug
While using number input from forms, user cannot clear it and it will always have `0` as value

### To Reproduce
Provide step-by-step instructions to reproduce the bug:

1. Go to [forms](https://www.medlycomponents.com/?path=/docs/forms-basic--form#form-with-all-the-field-types)
2. Click on **database** under **Marks**
3. Enter a number eg: **12345**
4. Try to clear the input to have no value
5. See error i.e. it always contains `0` as a value

### Expected behavior
While clearing an input it should not contain `0` value. User should be able to completely clear the input

### Screenshots

https://user-images.githubusercontent.com/43134750/158786458-0c258035-6baa-4770-9a73-372e819a0237.mov

### PR DESCRIPTION
**Pull request by PulkitBanta**
# PR Checklist

## Description
Allow user to clear number input after entering a number

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes and API changes)
- [ ] Build changes
- [ ] CI changes
- [ ] Document content changes
- [ ] Performance improvement
- [ ] Add missing tests
- [ ] Others (please describe)

## What is the current behaviour?
Once you enter a number in number input, user is now allowed to clear it and there is always a value `0` set

## What is the new behaviour?
User can clear the number input

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/forms/src/hooks/useForm/useForm.ts [hunk 1]
```diff
@@ -68,7 +68,7 @@ export const useForm = (initialState: Record<string, unknown>): UseFormResult =>
     const handleNumberChange: Handlers['handleNumberChange'] = useCallback(
         memoize(name => event => {
             const { value } = event.target as HTMLInputElement;
-            setValues(val => ({ ...val, [name]: Number(value) }));
+            setValues(val => ({ ...val, [name]: !value ? undefined : Number(value) }));
```
Comment (gmukul01) [inline packages/forms/src/hooks/useForm/useForm.ts:71]:
```suggestion
            setValues(val => ({ ...val, [name]: Number(value) || undefined }));
```

**Review by gmukul01 — APPROVED** [review]
