### PR TITLE
fix: modal close issue on click on outside of modal

### LINKED ISSUE #688: bug: Select field option list doesn't get change when used inside modal form component..
### Describe the bug
We have created Modal having form component inside it & our form has single select field which is for selecting state.
When user click on select field then options get visible to the user but if user click outside of that options but inside of modal or select on any other form field then also option remains visible. Ideally it should get hide.

It works as expected if we click outside of modal but it doesn't work if we click anywhere inside modal.

### To Reproduce
Provide step-by-step instructions to reproduce the bug:

1. Create Modal having form component inside Modal.Content.
2. Form component should contained at least one single select field in it e.g. Select State.
3. Then See this component on ui then you will get to know about this bug.

### Expected behavior
Ideally it should get hide if user click anywhere out side select options of the field.

### Screenshots
If applicable, provide screenshots to explain the bug.
image

### Package versions
 - @medly-components/core : 
 - @medly-components/forms : 
 - @medly-components/icons : 
 - @medly-components/layout : 
 - @medly-components/loaders : 
 - @medly-components/theme : 
 - @medly-components/utils : 

### Additional context
Provide any additional information about the bug or the bug scenario.

### PR DESCRIPTION
**Pull request by gmukul01**
affects: @medly-components/core

ISSUES CLOSED: #688

# PR Checklist

## Description
Handles the issue of modal being closed on click on outside of modal and also the issue of closing the singleSelect on clicking on outside of single select component.

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes and API changes)
- [ ] Build changes
- [ ] CI changes
- [ ] Document content changes
- [ ] Performance improvement
- [ ] Add missing tests
- [ ] Others (please describe)

## What is the current behaviour?
On Clicking outside of any SingleSelect component which is being used in Modal is not closing the dropdown.

## What is the new behaviour?
Now Clicking outside of any SingleSelect component which is being used in Modal is closing the dropdown.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

**Note:** (Replace This Text: If this PR contains a breaking change please describe the impact and migration path for existing application.)

## Additional context
(Replace This Text: Please describe any other related information or add screenshots of the PR.)

## Checklist

- [x] My code follows the style guidelines of this project

- [x] I have performed a self-review of my own code

- [ ] I have commented my code, particularly in hard-to-understand areas

- [ ] I have made corresponding changes to the documentation

- [x] My changes generate no new warnings

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] New and existing unit tests pass locally with my changes

- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: packages/core/src/components/Modal/Modal.tsx [hunk 1]
```diff
@@ -42,9 +42,11 @@ const Component: FC<ModalProps> = memo(
                 if (modalRef.current) manager.remove(modalRef.current);
                 onCloseModal && onCloseModal();
             }, [onCloseModal, manager]),
-            handleBackgroundClick = useCallback(() => {
-                shouldCloseOnOutsideClick && handleCloseModal();
-            }, [shouldCloseOnOutsideClick, handleCloseModal]),
+            handleBackgroundClick = useCallback(
+                (event: React.MouseEvent<HTMLDivElement>) =>
```
Comment (abhishekashyap) [inline packages/core/src/components/Modal/Modal.tsx:46]: Minor detail, but we can get rid of the React object and import the MouseEvent from the import statement

**Review by abhishekashyap — APPROVED** [review]

**Review by PulkitBanta — APPROVED** [review]
